CREATE DATABASE IF NOT EXISTS solar_inverter;
USE solar_inverter;

CREATE TABLE inverter_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    state VARCHAR(50),
    vac_l1 DECIMAL(6,2),
    vac_l2 DECIMAL(6,2),
    vac_l3 DECIMAL(6,2),
    iac_l1 DECIMAL(6,3),
    iac_l2 DECIMAL(6,3),
    iac_l3 DECIMAL(6,3),
    freq1 DECIMAL(5,2),
    freq2 DECIMAL(5,2),
    freq3 DECIMAL(5,2),
    pac1 INT,
    pac2 INT,
    pac3 INT,
    p_ac INT,
    temp DECIMAL(4,1),
    e_today DECIMAL(8,2),
    t_today DECIMAL(6,1),
    e_total DECIMAL(12,2),
    co2 DECIMAL(12,2),
    t_total DECIMAL(12,1),
    v_pv1 DECIMAL(6,1),
    v_pv2 DECIMAL(6,1),
    v_pv3 DECIMAL(6,1),
    v_bus DECIMAL(6,1),
    max_power INT,
    i_pv11 DECIMAL(6,3),
    i_pv12 DECIMAL(6,3),
    i_pv13 DECIMAL(6,3),
    i_pv14 DECIMAL(6,3),
    i_pv21 DECIMAL(6,3),
    i_pv22 DECIMAL(6,3),
    i_pv23 DECIMAL(6,3),
    i_pv24 DECIMAL(6,3),
    i_pv31 DECIMAL(6,3),
    i_pv32 DECIMAL(6,3),
    i_pv33 DECIMAL(6,3),
    i_pv34 DECIMAL(6,3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp (timestamp),
    INDEX idx_state (state),
    INDEX idx_created_at (created_at)
);

CREATE TABLE collection_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    status ENUM('success', 'error', 'warning') NOT NULL,
    message TEXT,
    execution_time_ms INT,
    records_processed INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp (timestamp),
    INDEX idx_status (status)
);

CREATE TABLE p1_devices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    unique_id VARCHAR(100) UNIQUE NOT NULL,
    meter_model VARCHAR(100),
    smr_version TINYINT UNSIGNED,
    wifi_ssid VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_unique_id (unique_id)
);

CREATE TABLE p1_meter_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    device_id INT NOT NULL,
    timestamp DATETIME NOT NULL,
    wifi_strength TINYINT UNSIGNED,
    active_tariff TINYINT UNSIGNED,
    total_power_import_kwh DECIMAL(10,3),
    total_power_import_t1_kwh DECIMAL(10,3),
    total_power_import_t2_kwh DECIMAL(10,3),
    total_power_export_kwh DECIMAL(10,3),
    total_power_export_t1_kwh DECIMAL(10,3),
    total_power_export_t2_kwh DECIMAL(10,3),
    active_power_w DECIMAL(8,3),
    active_power_l1_w DECIMAL(8,3),
    active_power_l2_w DECIMAL(8,3),
    active_power_l3_w DECIMAL(8,3),
    active_voltage_l1_v DECIMAL(5,1),
    active_voltage_l2_v DECIMAL(5,1),
    active_voltage_l3_v DECIMAL(5,1),
    active_current_a DECIMAL(6,3),
    active_current_l1_a DECIMAL(6,3),
    active_current_l2_a DECIMAL(6,3),
    active_current_l3_a DECIMAL(6,3),
    voltage_sag_l1_count INT UNSIGNED DEFAULT 0,
    voltage_sag_l2_count INT UNSIGNED DEFAULT 0,
    voltage_sag_l3_count INT UNSIGNED DEFAULT 0,
    voltage_swell_l1_count INT UNSIGNED DEFAULT 0,
    voltage_swell_l2_count INT UNSIGNED DEFAULT 0,
    voltage_swell_l3_count INT UNSIGNED DEFAULT 0,
    any_power_fail_count INT UNSIGNED DEFAULT 0,
    long_power_fail_count INT UNSIGNED DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (device_id) REFERENCES p1_devices(id),
    INDEX idx_device_timestamp (device_id, timestamp),
    INDEX idx_timestamp (timestamp),
    INDEX idx_active_tariff (active_tariff),
    INDEX idx_created_at (created_at)
);