CREATE DATABASE IF NOT EXISTS solar_inverter;
USE solar_inverter;

CREATE TABLE inverter_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    state VARCHAR(50),
    vac_l1 DECIMAL(6,2),
    vac_l2 DECIMAL(6,2),
    vac_l3 DECIMAL(6,2),
    iac_l1 DECIMAL(6,3),
    iac_l2 DECIMAL(6,3),
    iac_l3 DECIMAL(6,3),
    freq1 DECIMAL(5,2),
    freq2 DECIMAL(5,2),
    freq3 DECIMAL(5,2),
    pac1 INT,
    pac2 INT,
    pac3 INT,
    p_ac INT,
    temp DECIMAL(4,1),
    e_today DECIMAL(8,2),
    t_today DECIMAL(6,1),
    e_total DECIMAL(12,2),
    co2 DECIMAL(12,2),
    t_total DECIMAL(12,1),
    v_pv1 DECIMAL(6,1),
    v_pv2 DECIMAL(6,1),
    v_pv3 DECIMAL(6,1),
    v_bus DECIMAL(6,1),
    max_power INT,
    i_pv11 DECIMAL(6,3),
    i_pv12 DECIMAL(6,3),
    i_pv13 DECIMAL(6,3),
    i_pv14 DECIMAL(6,3),
    i_pv21 DECIMAL(6,3),
    i_pv22 DECIMAL(6,3),
    i_pv23 DECIMAL(6,3),
    i_pv24 DECIMAL(6,3),
    i_pv31 DECIMAL(6,3),
    i_pv32 DECIMAL(6,3),
    i_pv33 DECIMAL(6,3),
    i_pv34 DECIMAL(6,3),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp (timestamp),
    INDEX idx_state (state),
    INDEX idx_created_at (created_at)
);

CREATE TABLE collection_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    status ENUM('success', 'error', 'warning') NOT NULL,
    message TEXT,
    execution_time_ms INT,
    records_processed INT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_timestamp (timestamp),
    INDEX idx_status (status)
);