name: Deploy Solar Inverter Collector

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to production server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        port: ${{ secrets.PROD_PORT || 22 }}
        script: |
          set -e

          # Configuration
          REPO_URL="${{ github.server_url }}/${{ github.repository }}"
          DEPLOY_DIR="/tmp/solar-deploy-$(date +%s)"
          APP_DIR="$HOME/solar-inverter"
          SERVICE_NAME="solar-inverter-collector"

          echo "🚀 Starting deployment..."

          # Clone the repository
          echo "📥 Cloning repository..."
          git clone --depth 1 --branch main "$REPO_URL" "$DEPLOY_DIR"
          cd "$DEPLOY_DIR"

          # Stop the service during deployment
          echo "⏸️ Stopping service..."
          systemctl --user stop ${SERVICE_NAME}.timer || true

          # Backup current installation if it exists
          if [ -d "$APP_DIR" ]; then
            echo "💾 Creating backup..."
            cp -r "$APP_DIR" "${APP_DIR}.backup.$(date +%Y%m%d_%H%M%S)"
          fi

          # Update application files (preserve config and logs)
          echo "📂 Updating application files..."
          mkdir -p "$APP_DIR"

          # Copy new files
          cp collect_solar_data.py "$APP_DIR/"
          cp setup_database.py "$APP_DIR/"
          cp requirements.txt "$APP_DIR/"
          cp monitor.sh "$APP_DIR/"
          chmod +x "$APP_DIR"/*.py "$APP_DIR"/*.sh

          # Update Python dependencies
          echo "🐍 Updating Python dependencies..."
          "$APP_DIR/venv/bin/pip" install -r "$APP_DIR/requirements.txt"

          # Start the service
          echo "▶️ Starting service..."
          systemctl --user daemon-reload
          systemctl --user start ${SERVICE_NAME}.timer

          # Verify deployment
          echo "✅ Verifying deployment..."
          sleep 5
          systemctl --user status ${SERVICE_NAME}.timer --no-pager -l

          # Test data collection
          echo "🧪 Testing data collection..."
          if timeout 30 "$APP_DIR/venv/bin/python" "$APP_DIR/collect_solar_data.py"; then
            echo "✅ Test collection successful"
          else
            echo "❌ Test collection failed"
            exit 1
          fi

          # Cleanup
          echo "🧹 Cleaning up..."
          rm -rf "$DEPLOY_DIR"

          echo "🎉 Deployment completed successfully!"
          echo "📊 Service status:"
          systemctl --user status ${SERVICE_NAME}.timer --no-pager -l